sudo: false
dist: trusty
language: node_js
node_js:
  - 7
  - 8
  - 9
  - node

cache:
  directories:
    - node_modules

notifications:
  email:
    on_failure: change

install:
  - npm install

script:
  - npm run test

before_deploy:
  - npm run bundle

deploy:
  provider: npm
  email: remi@cliqz.com
  skip_cleanup: true
  api_key:
    secure: "DO4UwK8m4oeapKyVKJYS9PJpTjJ/5fyp+WjeqFx6zwp5XSNUgFxjOhGkrD6ZkSAu4CxeAIrfbrh0KJTPCWkC22+IjxhlJWICgjfCmbyvoZpC4VysyJMbgyQOcg5UjsqcvKTK1bRAMCCyZOYZH4Wo8hXh2F/9LNk6QJeqQWhFqybD0s6gQApj/jVVENfzREH0DPl1SChySJDYVqbvRlJKihmZYL5oizBCEUWVGuoPbPkdl5OeKZ+EcPSpCAaPasD/RDmixOdYURo/jMra0o5Q0rUMmTeBlS71Mix18ZmCFeDpeckFDAiRP46hXNKIlAsWFxFPhgy4sq9nN2kyd6SwdBCnLcGR+u+ropFAWFxDhRlar9yI7pmUJqWJBqK1yVv4aaQCEl0kP0qTAbzoT77mA8DyPYZNuriQWhIjKwRkP4VAawBUTNxudv4R5ivH3kZhhkMGEAvOZ+dbhsZwlCgvcQC+MA7VFjvUZT8/89oLntNrW81RSNGU+fO6DigQLpOiweqo/Lq1WxGejOhyqaE3xd3Hva5XE9AzYx/7LSMmGPeRvp4AgknkC68L9X+uLUO17q1sX6DLgdABjSx94Tjh+bboDavvMcwQ2jEXblREfLvtIbcKGTTQJaL9zM12V/Qv8yW9KymLKZFw1o5kPKyiT4CzCzzMNDdsHzpL8geVTrg="
  on:
    branch: master
    tags: true
    repo: cliqz-oss/adblocker
