version: 1

update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    version_requirement_updates: widen_ranges
    default_reviewers:
      - "remusao"
    default_labels:
      - "PR: Internal :house:"
      - "dependencies"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
